<a href="https://colab.research.google.com/github/poppatheduke/Deep-Machine-Learning/blob/master/Sound_to_text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade transformers

In [ ]:
import transformers
print(transformers.__version__)

4.38.2


In [ ]:
import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
import numpy as np

In [ ]:
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.60k [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.10/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:733: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of the model checkpoint at facebook/wav2vec2-base-960h were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.encoder.pos_conv_embed.conv.weight_g', 'wav2vec2.encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.masked_spec_embed']
You sho

In [ ]:
#load audio file
audio, sampling_rate = librosa.load("./20240313-115628.mp3", sr=16000)

In [ ]:
audio,sampling_rate

(array([-6.76730144e-16,  1.07125845e-16,  6.83025092e-15, ...,
        -1.78258313e-04,  4.17988922e-04,  0.00000000e+00], dtype=float32),
 16000)

In [ ]:
# audio
display.Audio("./20240313-115628.mp3", autoplay=True)

In [ ]:
input_values = tokenizer(audio, return_tensors = 'pt').input_values
input_values

tensor([[ 0.0018,  0.0018,  0.0018,  ..., -0.0019,  0.0102,  0.0018]])

In [ ]:
# store logits (non-normalized predictions)
logits = model(input_values).logits
logits

tensor([[[ 11.2373, -23.8176, -23.5570,  ...,  -5.2447,  -6.4462,  -5.7691],
         [ 11.2633, -23.8372, -23.5769,  ...,  -5.2437,  -6.4348,  -5.7541],
         [ 11.2817, -23.8663, -23.6077,  ...,  -5.2645,  -6.4312,  -5.7493],
         ...,
         [ 11.4257, -23.8576, -23.5978,  ...,  -5.3394,  -7.0075,  -5.6734],
         [ 11.3831, -23.8080, -23.5503,  ...,  -5.3111,  -7.0330,  -5.6679],
         [ 11.3179, -23.7706, -23.5163,  ...,  -5.2893,  -7.0002,  -5.6645]]],
       grad_fn=<ViewBackward0>)

In [ ]:
# store predicted id's
# pass the logit values to softmax to get the predicted values
predicted_ids = torch.argmax(logits, dim =-1)

In [ ]:
# pass the prediction to the tokenzer decode to get the transcription
transcriptions = tokenizer.decode(predicted_ids[0])

In [ ]:
transcriptions

'HALLO KEEP ON SEARCIN'